name: Checks
on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Test and lint
    runs-on: ubuntu-latest
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          # Semantic version range syntax or exact version of a Python version
          python-version: '3.13.2'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Install dev dependencies
        run: pip install -r requirements.dev.txt
      - name: Install test dependencies
        run: pip install -r requirements.test.txt
      - name: Lint with flake8
        run: flake8
      - name: Static type checking with mypy
        run: mypy . --strict
      - name: Test
        run: pytest
      - name: Build Docker image
        run: docker build .